#############################################################################
# Makefile for building: bin/game
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  novella.pro
# Template: app
# Command: /home/dogusakov/Programms/Qt/5.7/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile novella.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I../../../Programms/Qt/5.7/gcc_64/include -I../../../Programms/Qt/5.7/gcc_64/include/QtWidgets -I../../../Programms/Qt/5.7/gcc_64/include/QtGui -I../../../Programms/Qt/5.7/gcc_64/include/QtSerialPort -I../../../Programms/Qt/5.7/gcc_64/include/QtCore -Ibuild/moc -Ibuild/ui -I../../../Programms/Qt/5.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/dogusakov/Programms/Qt/5.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = game1.0.0
DISTDIR = /home/dogusakov/Designed_project/Game/MyNovella/build/objects/game1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/dogusakov/Programms/Qt/5.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/dogusakov/Programms/Qt/5.7/gcc_64/lib -lQt5Widgets -L/usr/lib64 -lQt5Gui -lQt5SerialPort -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/objects/

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/preference.cpp build/res/qrc_res.cpp \
		build/moc/moc_mainwindow.cpp \
		build/moc/moc_preference.cpp
OBJECTS       = build/objects/main.o \
		build/objects/mainwindow.o \
		build/objects/preference.o \
		build/objects/qrc_res.o \
		build/objects/moc_mainwindow.o \
		build/objects/moc_preference.o
DIST          = ../../../Programms/Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/uic.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		novella.pro include/headernovella.h \
		include/mainwindow.h \
		include/preference.h \
		include/preferencecss.h src/main.cpp \
		src/mainwindow.cpp \
		src/preference.cpp
QMAKE_TARGET  = game
DESTDIR       = bin/
TARGET        = bin/game


first: all
####### Build rules

$(TARGET): build/ui/ui_mainwindow.h build/ui/ui_preference.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: novella.pro ../../../Programms/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Programms/Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/unix.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/linux.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/sanitize.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/g++-base.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/qconfig.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt_config.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/default_pre.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/default_post.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/warn_on.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/resources.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/moc.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/uic.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/file_copies.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/exceptions.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/yacc.prf \
		../../../Programms/Qt/5.7/gcc_64/mkspecs/features/lex.prf \
		novella.pro \
		resources/res.qrc \
		../../../Programms/Qt/5.7/gcc_64/lib/libQt5Widgets.prl \
		../../../Programms/Qt/5.7/gcc_64/lib/libQt5Gui.prl \
		../../../Programms/Qt/5.7/gcc_64/lib/libQt5SerialPort.prl \
		../../../Programms/Qt/5.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile novella.pro
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/spec_pre.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/common/unix.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/common/linux.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/common/sanitize.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/common/gcc-base.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/common/g++-base.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/common/g++-unix.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/qconfig.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt_functions.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt_config.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/default_pre.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/resolve_config.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/default_post.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qml_debug.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/warn_on.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/qt.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/resources.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/moc.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/uic.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/unix/thread.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/file_copies.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/exceptions.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/yacc.prf:
../../../Programms/Qt/5.7/gcc_64/mkspecs/features/lex.prf:
novella.pro:
resources/res.qrc:
../../../Programms/Qt/5.7/gcc_64/lib/libQt5Widgets.prl:
../../../Programms/Qt/5.7/gcc_64/lib/libQt5Gui.prl:
../../../Programms/Qt/5.7/gcc_64/lib/libQt5SerialPort.prl:
../../../Programms/Qt/5.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile novella.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents include/headernovella.h include/mainwindow.h include/preference.h include/preferencecss.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/preference.cpp $(DISTDIR)/
	$(COPY_FILE) --parents gui/mainwindow.ui gui/preference.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/res/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/res/qrc_res.cpp
build/res/qrc_res.cpp: resources/res.qrc \
		../../../Programms/Qt/5.7/gcc_64/bin/rcc \
		resources/image/background/mm_bg_quit.jpg \
		resources/image/background/night.jpg \
		resources/image/background/bg.jpg \
		resources/image/background/day.jpg \
		resources/image/background/evening.jpg \
		resources/image/background/morning.jpg \
		resources/file/novel800x600.css \
		resources/image/elements/bar_u_full_hover.png \
		resources/image/elements/Preference/b_all_mesage_selected_idle.png \
		resources/image/elements/Preference/b_read_mesage_hover.png \
		resources/image/elements/Preference/exit_idle.png \
		resources/image/elements/Preference/b_read_mesage_idle.png \
		resources/image/elements/Preference/b_begin_skip_hover.png \
		resources/image/elements/Preference/b_window_selected_idle.png \
		resources/image/elements/Preference/b_nothing_idle.png \
		resources/image/elements/Preference/b_all_idle.png \
		resources/image/elements/Preference/b_fullscreen_selected_idle.png \
		resources/image/elements/Preference/b_stop_skip_hover.png \
		resources/image/elements/Preference/save_p_idle.png \
		resources/image/elements/Preference/b_window_idle.png \
		resources/image/elements/Preference/b_read_mesage_selected_idle.png \
		resources/image/elements/Preference/save_p_hover.png \
		resources/image/elements/Preference/b_fullscreen_idle.png \
		resources/image/elements/Preference/b_next_skip_idle.png \
		resources/image/elements/Preference/home_idle.png \
		resources/image/elements/Preference/exit_hover.png \
		resources/image/elements/Preference/back_hover.png \
		resources/image/elements/Preference/b_next_skip_selected_idle.png \
		resources/image/elements/Preference/b_stop_skip_idle.png \
		resources/image/elements/Preference/b_all_hover.png \
		resources/image/elements/Preference/b_nothing_selected_idle.png \
		resources/image/elements/Preference/b_begin_skip_idle.png \
		resources/image/elements/Preference/load_p_hover.png \
		resources/image/elements/Preference/b_all_selected_idle.png \
		resources/image/elements/Preference/home_insensitive.png \
		resources/image/elements/Preference/back_idle.png \
		resources/image/elements/Preference/b_next_skip_hover.png \
		resources/image/elements/Preference/b_fullscreen_hover.png \
		resources/image/elements/Preference/options_selected_idle.png \
		resources/image/elements/Preference/save_p_insensitive.png \
		resources/image/elements/Preference/b_all_mesage_idle.png \
		resources/image/elements/Preference/b_stop_skip_selected_idle.png \
		resources/image/elements/Preference/b_window_hover.png \
		resources/image/elements/Preference/b_nothing_hover.png \
		resources/image/elements/Preference/home_hover.png \
		resources/image/elements/Preference/b_begin_skip_insensitive.png \
		resources/image/elements/Preference/b_all_mesage_hover.png \
		resources/image/elements/Preference/load_p_idle.png \
		resources/image/elements/Menu/exit_hover.png \
		resources/image/elements/Menu/new_game_hover.png \
		resources/image/elements/Menu/load_idle.png \
		resources/image/elements/Menu/new_game_idle.png \
		resources/image/elements/Menu/exit_idle.png \
		resources/image/elements/Menu/options_hover.png \
		resources/image/elements/Menu/load_hover.png \
		resources/image/elements/Menu/options_idle.png
	/home/dogusakov/Programms/Qt/5.7/gcc_64/bin/rcc -name res resources/res.qrc -o build/res/qrc_res.cpp

compiler_moc_header_make_all: build/moc/moc_mainwindow.cpp build/moc/moc_preference.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_mainwindow.cpp build/moc/moc_preference.cpp
build/moc/moc_mainwindow.cpp: ../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qicon.h \
		include/headernovella.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QTextEdit \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qframe.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextdocument.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QTime \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/QBitmap \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbitmap.h \
		include/preference.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QWidget \
		include/preferencecss.h \
		include/mainwindow.h \
		../../../Programms/Qt/5.7/gcc_64/bin/moc
	/home/dogusakov/Programms/Qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/dogusakov/Programms/Qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/dogusakov/Designed_project/Game/MyNovella -I/home/dogusakov/Designed_project/Game/MyNovella/include -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtWidgets -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtGui -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtSerialPort -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/mainwindow.h -o build/moc/moc_mainwindow.cpp

build/moc/moc_preference.cpp: ../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QWidget \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		include/headernovella.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QTextEdit \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qframe.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextdocument.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QTime \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/QBitmap \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbitmap.h \
		include/preferencecss.h \
		include/preference.h \
		../../../Programms/Qt/5.7/gcc_64/bin/moc
	/home/dogusakov/Programms/Qt/5.7/gcc_64/bin/moc $(DEFINES) -I/home/dogusakov/Programms/Qt/5.7/gcc_64/mkspecs/linux-g++ -I/home/dogusakov/Designed_project/Game/MyNovella -I/home/dogusakov/Designed_project/Game/MyNovella/include -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtWidgets -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtGui -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtSerialPort -I/home/dogusakov/Programms/Qt/5.7/gcc_64/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include include/preference.h -o build/moc/moc_preference.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui/ui_mainwindow.h build/ui/ui_preference.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui/ui_mainwindow.h build/ui/ui_preference.h
build/ui/ui_mainwindow.h: gui/mainwindow.ui \
		../../../Programms/Qt/5.7/gcc_64/bin/uic
	/home/dogusakov/Programms/Qt/5.7/gcc_64/bin/uic gui/mainwindow.ui -o build/ui/ui_mainwindow.h

build/ui/ui_preference.h: gui/preference.ui \
		../../../Programms/Qt/5.7/gcc_64/bin/uic
	/home/dogusakov/Programms/Qt/5.7/gcc_64/bin/uic gui/preference.ui -o build/ui/ui_preference.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/objects/main.o: src/main.cpp include/mainwindow.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qicon.h \
		include/headernovella.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QTextEdit \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qframe.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextdocument.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QTime \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/QBitmap \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbitmap.h \
		include/preference.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QWidget \
		include/preferencecss.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QApplication \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/main.o src/main.cpp

build/objects/mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QMainWindow \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qmainwindow.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qicon.h \
		include/headernovella.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QTextEdit \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qframe.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextdocument.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QTime \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/QBitmap \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbitmap.h \
		include/preference.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QWidget \
		include/preferencecss.h \
		build/ui/ui_mainwindow.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QAction \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qaction.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QApplication \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qinputmethod.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QButtonGroup \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QHeaderView \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qheaderview.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qstyleoption.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qvalidator.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qregularexpression.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qslider.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractslider.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qstyle.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtabbar.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qrubberband.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QPushButton \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qpushbutton.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/mainwindow.o src/mainwindow.cpp

build/objects/preference.o: src/preference.cpp include/preference.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QWidget \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobal.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qconfig.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfeatures.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtypetraits.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qisenum.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsysinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlogging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qflags.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmutex.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnumeric.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qversiontagging.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qnamespace.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstring.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qchar.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrefcount.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qarraydata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qalgorithms.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiterator.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpair.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringlist.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qregexp.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmetatype.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qobject_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmargins.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qrect.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsize.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qpoint.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpalette.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcolor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgb.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qrgba64.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbrush.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvector.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qmatrix.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpolygon.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qregion.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatastream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qiodevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qline.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtransform.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpainterpath.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qimage.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixelformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpixmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qshareddata.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qhash.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfont.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qfontinfo.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qkeysequence.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qevent.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qvariant.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qmap.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdebug.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qtextstream.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qlocale.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qset.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurl.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qurlquery.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfile.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qfiledevice.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qvector2d.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtouchdevice.h \
		include/headernovella.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QTextEdit \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtextedit.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qframe.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextdocument.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextoption.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextcursor.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qtextformat.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qpen.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QTime \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qdatetime.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QFile \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QDebug \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/QBitmap \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qbitmap.h \
		include/preferencecss.h \
		build/ui/ui_preference.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/QVariant \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QAction \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qaction.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qicon.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qactiongroup.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QApplication \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qeventloop.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qguiapplication.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qinputmethod.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QButtonGroup \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QFrame \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QHeaderView \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qheaderview.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qstyleoption.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtGui/qvalidator.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtCore/qregularexpression.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qslider.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractslider.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qstyle.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtabbar.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qtabwidget.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qrubberband.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QLabel \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qlabel.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/QPushButton \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qpushbutton.h \
		../../../Programms/Qt/5.7/gcc_64/include/QtWidgets/qabstractbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/preference.o src/preference.cpp

build/objects/qrc_res.o: build/res/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/qrc_res.o build/res/qrc_res.cpp

build/objects/moc_mainwindow.o: build/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/moc_mainwindow.o build/moc/moc_mainwindow.cpp

build/objects/moc_preference.o: build/moc/moc_preference.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/objects/moc_preference.o build/moc/moc_preference.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

